$(".loginWrapper>.back>span").on('click',function(){
    $(".loginWrapper").toggleClass("animate");
    $(".registerWrapper").toggleClass("animate");
    console.log("注册");
});
$(".registerWrapper>.back>span").on('click',function(){
    $(".loginWrapper").toggleClass("animate");
    $(".registerWrapper").toggleClass("animate");
    console.log("登录");
});
